# Generated by Django 4.2 on 2023-05-03 08:55

import dbquery_practice.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Standard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard', models.CharField(db_index=True, max_length=256)),
                ('subject', models.CharField(db_index=True, max_length=256)),
            ],
            options={
                'verbose_name': 'standard',
                'verbose_name_plural': 'standards',
                'db_table': 'standard',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(upload_to=dbquery_practice.models.image_content, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg'])], verbose_name='student_image')),
                ('first_name', models.CharField(db_index=True, max_length=256)),
                ('last_name', models.CharField(db_index=True, max_length=256)),
                ('hobby', models.CharField(db_index=True, max_length=256)),
                ('email', models.EmailField(db_index=True, max_length=256, unique=True)),
                ('contect_no', models.CharField(db_index=True, help_text='enter 10 digit number', max_length=10, unique=True)),
                ('standard', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_standard', to='dbquery_practice.standard')),
            ],
            options={
                'verbose_name': 'student',
                'verbose_name_plural': 'students',
                'db_table': 'student',
            },
        ),
    ]
